// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2c224e7e-3ef5-431d-a57b-e71f4662e3a6',
    name: 'Node CLI Test',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: ['mobileservice'],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_TEST_LOCATION'] = 'West Europe';
};

exports.scopes = [[function (nock) { 
var result = 
nock('https://cliteststorage6387.blob.core.windows.net:443')
  .get('/testfilecopysourcecontainer?restype=container&comp=acl')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><SignedIdentifiers />", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  'last-modified': 'Wed, 07 Sep 2016 12:05:53 GMT',
  etag: '"0x8D3D717516C6F3F"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '71dca33f-0001-007b-2500-093274000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:05:58 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage6387.file.core.windows.net:443')
  .put('/testfilecopydestshare/testfilecopydestdir/toCopy')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:06:00 GMT',
  etag: '"0x8D3D717550C6024"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2dc437db-001a-0049-4600-096aa4000000',
  'x-ms-version': '2015-04-05',
  'x-ms-copy-id': 'ec9c5893-32bd-4008-af65-fda2a4a33ec7',
  'x-ms-copy-status': 'pending',
  date: 'Wed, 07 Sep 2016 12:06:00 GMT' });
 return result; }]];