// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2c224e7e-3ef5-431d-a57b-e71f4662e3a6',
    name: 'Node CLI Test',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: ['mobileservice'],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_TEST_LOCATION'] = 'West Europe';
};

exports.scopes = [[function (nock) { 
var result = 
nock('https://cliteststorage6387.file.core.windows.net:443')
  .head('/filetestshare/remotefile')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'db971c89-001a-000b-2900-0941b0000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:05:46 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage6387.file.core.windows.net:443')
  .head('/filetestshare/remotefile?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '57b81755-001a-00bc-4a00-094eb5000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:05:46 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage6387.file.core.windows.net:443')
  .head('/filetestshare?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:05:47 GMT',
  etag: '"0x8D3D7174DAB87B9"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '53c38899-001a-0002-1300-095b3e000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:05:46 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage6387.file.core.windows.net:443')
  .head('/filetestshare/remotefile')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '083c202a-001a-004f-5e00-099ddc000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:05:47 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage6387.file.core.windows.net:443')
  .put('/filetestshare/remotefile')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:05:48 GMT',
  etag: '"0x8D3D7174DF6FAEE"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '8e8489c2-001a-00a6-5f00-0961da000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:05:47 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage6387.file.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/filetestshare/remotefile?comp=range', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'BLb4bUlxavjU8u3wGjCfyA==',
  'last-modified': 'Wed, 07 Sep 2016 12:05:48 GMT',
  etag: '"0x8D3D7174E1B0672"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '523323ae-001a-001d-5200-09802e000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:05:48 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage6387.file.core.windows.net:443')
  .put('/filetestshare/remotefile?comp=properties')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:05:48 GMT',
  etag: '"0x8D3D7174E4A5F4B"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e9c0fdbd-001a-0032-7c00-090114000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:05:48 GMT' });
 return result; }]];