// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2c224e7e-3ef5-431d-a57b-e71f4662e3a6',
    name: 'Node CLI Test',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: ['mobileservice'],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_TEST_LOCATION'] = 'West Europe';
};

exports.scopes = [[function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .put('/storage-cli-blob-test/appendblobname2369?comp=snapshot')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:01:39 GMT',
  etag: '"0x8D3D716B99BF565"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '427f03fb-0001-006b-58ff-080492000000',
  'x-ms-version': '2015-04-05',
  'x-ms-snapshot': '2016-09-07T12:01:56.2809886Z',
  date: 'Wed, 07 Sep 2016 12:01:55 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .put('/storage-cli-blob-test/appendblobname2369?comp=snapshot')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:01:39 GMT',
  etag: '"0x8D3D716B99BF565"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '35e5db96-0001-00d8-6eff-08fe15000000',
  'x-ms-version': '2015-04-05',
  'x-ms-snapshot': '2016-09-07T12:01:56.6533382Z',
  date: 'Wed, 07 Sep 2016 12:01:56 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .put('/storage-cli-blob-test/appendblobname2369?comp=snapshot')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:01:39 GMT',
  etag: '"0x8D3D716B99BF565"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2fafec98-0001-00fb-1fff-0891de000000',
  'x-ms-version': '2015-04-05',
  'x-ms-snapshot': '2016-09-07T12:01:57.0877484Z',
  date: 'Wed, 07 Sep 2016 12:01:57 GMT' });
 return result; }]];