// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2c224e7e-3ef5-431d-a57b-e71f4662e3a6',
    name: 'Node CLI Test',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: ['mobileservice'],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_TEST_LOCATION'] = 'West Europe';
};

exports.scopes = [[function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .head('/testblobcopydest/testblobcopydir/copytoblob.tmp.txt')
  .reply(200, "", { 'content-length': '10',
  'last-modified': 'Wed, 07 Sep 2016 12:03:10 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D3D716F040EC1B"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '90adf123-0001-00a5-16ff-0862dd000000',
  'x-ms-version': '2015-04-05',
  'x-ms-write-protection': 'false',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-copy-id': 'cad2f277-d301-4318-837f-5f392c0f02b7',
  'x-ms-copy-source': 'https://cliteststorage2874.file.core.windows.net/testblobcopyshare/testblobcopydir/copytoblob.tmp.txt?se=2016-09-14T12%3A03%3A11Z&sp=r&sv=2015-04-05&sr=f&sig=gze%2BFwhp4xMRCDq1gvYm296aqJDrNb%2B46DdDGTxaYZs%3D',
  'x-ms-copy-status': 'success',
  'x-ms-copy-progress': '10/10',
  'x-ms-copy-completion-time': 'Wed, 07 Sep 2016 12:03:10 GMT',
  date: 'Wed, 07 Sep 2016 12:03:10 GMT' });
 return result; }]];