// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2c224e7e-3ef5-431d-a57b-e71f4662e3a6',
    name: 'Node CLI Test',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: ['mobileservice'],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_TEST_LOCATION'] = 'West Europe';
};

exports.scopes = [[function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/pageblobname461317')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c285f35c-0001-00ea-2bff-08a6c5000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:01:37 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .put('/storage-cli-blob-test/pageblobname461317')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:01:36 GMT',
  etag: '"0x8D3D716B8397824"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '90a369fa-0001-00c6-57ff-0824f8000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:01:36 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/storage-cli-blob-test/pageblobname461317?comp=page', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'OToPoPNI+wOHGrk3JgV93A==',
  'last-modified': 'Wed, 07 Sep 2016 12:01:37 GMT',
  etag: '"0x8D3D716B85EE36C"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1a1d8f27-0001-0095-46ff-0838f7000000',
  'x-ms-version': '2015-04-05',
  'x-ms-blob-sequence-number': '0',
  date: 'Wed, 07 Sep 2016 12:01:36 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .put('/storage-cli-blob-test/pageblobname461317?comp=properties')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:01:37 GMT',
  etag: '"0x8D3D716B882EEE8"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '27f8a1e8-0001-00ee-15ff-085347000000',
  'x-ms-version': '2015-04-05',
  'x-ms-blob-sequence-number': '0',
  date: 'Wed, 07 Sep 2016 12:01:37 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/pageblobname461317')
  .reply(200, "", { 'content-length': '512',
  'content-type': 'application/octet-stream',
  'content-md5': 'OToPoPNI+wOHGrk3JgV93A==',
  'last-modified': 'Wed, 07 Sep 2016 12:01:37 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D3D716B882EEE8"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'a9223fd3-0001-0004-55ff-08ac46000000',
  'x-ms-version': '2015-04-05',
  'x-ms-write-protection': 'false',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  date: 'Wed, 07 Sep 2016 12:01:37 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/pageblobname461317')
  .reply(200, "", { 'content-length': '512',
  'content-type': 'application/octet-stream',
  'content-md5': 'OToPoPNI+wOHGrk3JgV93A==',
  'last-modified': 'Wed, 07 Sep 2016 12:01:37 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D3D716B882EEE8"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ff25f23a-0001-00b3-1eff-08a343000000',
  'x-ms-version': '2015-04-05',
  'x-ms-write-protection': 'false',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  date: 'Wed, 07 Sep 2016 12:01:37 GMT' });
 return result; }]];
 exports.randomTestIdsGenerated = function() { return ['pageblobname461317'];};