// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2c224e7e-3ef5-431d-a57b-e71f4662e3a6',
    name: 'Node CLI Test',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: ['mobileservice'],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_TEST_LOCATION'] = 'West Europe';
};

exports.scopes = [[function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .head('/testblobcopysource?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '448a4ba5-0001-0013-2fff-086c25000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:03:01 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .put('/testblobcopysource?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:03:02 GMT',
  etag: '"0x8D3D716EB11670C"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '8b1ae13c-0001-00f1-03ff-088857000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:03:02 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .head('/testblobcopydest?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1a4e77ef-0001-0062-53ff-081e1c000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:03:01 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .put('/testblobcopydest?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:03:03 GMT',
  etag: '"0x8D3D716EB86514B"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd8ebcd74-0001-0064-12ff-08e964000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:03:02 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/testblobcopysource/toCopy', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'aOEJ8PQMpyoV4FzCJ4b45g==',
  'last-modified': 'Wed, 07 Sep 2016 12:03:03 GMT',
  etag: '"0x8D3D716EB85C35D"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b9d015b2-0001-00da-66ff-08fcef000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:03:02 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.file.core.windows.net:443')
  .head('/testblobcopyshare?restype=share')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '18eefc87-001a-0086-42ff-080d16000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:03:02 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.file.core.windows.net:443')
  .put('/testblobcopyshare?restype=share')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:03:03 GMT',
  etag: '"0x8D3D716EC19298D"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '17bc1c74-001a-00a5-38ff-0862dd000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:03:03 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.file.core.windows.net:443')
  .head('/testblobcopyshare/testblobcopydir?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ad71153d-001a-00a4-01ff-086320000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:03:04 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.file.core.windows.net:443')
  .put('/testblobcopyshare/testblobcopydir?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:03:04 GMT',
  etag: '"0x8D3D716EC817B72"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '53c387f2-001a-0002-7eff-085b3e000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:03:03 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.file.core.windows.net:443')
  .put('/testblobcopyshare/testblobcopydir/copytoblob.tmp.txt')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:03:04 GMT',
  etag: '"0x8D3D716ECA5D51B"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fa03afbc-001a-000a-61ff-08404d000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:03:04 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.file.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/testblobcopyshare/testblobcopydir/copytoblob.tmp.txt?comp=range', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'aOEJ8PQMpyoV4FzCJ4b45g==',
  'last-modified': 'Wed, 07 Sep 2016 12:03:05 GMT',
  etag: '"0x8D3D716ECC9E097"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fa03afbe-001a-000a-62ff-08404d000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:03:04 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.file.core.windows.net:443')
  .put('/testblobcopyshare/testblobcopydir/copytoblob.tmp.txt?comp=properties')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:03:05 GMT',
  etag: '"0x8D3D716ECEFC14D"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '348f9e75-001a-00d4-01ff-0810e4000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:03:05 GMT' });
 return result; }]];