// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2c224e7e-3ef5-431d-a57b-e71f4662e3a6',
    name: 'Node CLI Test',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: ['mobileservice'],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_TEST_LOCATION'] = 'West Europe';
};

exports.scopes = [[function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .put('/storage-cli-blob-test/blockblobname695232365434740?comp=snapshot')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:01:49 GMT',
  etag: '"0x8D3D716BFB52D7C"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '6000e149-0001-005d-3bff-08a9c0000000',
  'x-ms-version': '2015-04-05',
  'x-ms-snapshot': '2016-09-07T12:01:53.7866468Z',
  date: 'Wed, 07 Sep 2016 12:01:53 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .put('/storage-cli-blob-test/blockblobname695232365434740?comp=snapshot')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:01:49 GMT',
  etag: '"0x8D3D716BFB52D7C"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '76bfe4ae-0001-000e-11ff-08b5cf000000',
  'x-ms-version': '2015-04-05',
  'x-ms-snapshot': '2016-09-07T12:01:54.1760135Z',
  date: 'Wed, 07 Sep 2016 12:01:54 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .put('/storage-cli-blob-test/blockblobname695232365434740?comp=snapshot')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:01:49 GMT',
  etag: '"0x8D3D716BFB52D7C"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f7669fe6-0001-0047-69ff-0886af000000',
  'x-ms-version': '2015-04-05',
  'x-ms-snapshot': '2016-09-07T12:01:54.5713836Z',
  date: 'Wed, 07 Sep 2016 12:01:54 GMT' });
 return result; }]];