// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2c224e7e-3ef5-431d-a57b-e71f4662e3a6',
    name: 'Node CLI Test',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: ['mobileservice'],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_TEST_LOCATION'] = 'West Europe';
};

exports.scopes = [[function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .put('/storage-cli-blob-test/pageblobname461317?comp=snapshot')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:01:37 GMT',
  etag: '"0x8D3D716B882EEE8"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fd23811b-0001-0015-3aff-089b5d000000',
  'x-ms-version': '2015-04-05',
  'x-ms-snapshot': '2016-09-07T12:01:55.0248090Z',
  date: 'Wed, 07 Sep 2016 12:01:54 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .put('/storage-cli-blob-test/pageblobname461317?comp=snapshot')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:01:37 GMT',
  etag: '"0x8D3D716B882EEE8"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0e4ec1ac-0001-003c-51ff-08ed1f000000',
  'x-ms-version': '2015-04-05',
  'x-ms-snapshot': '2016-09-07T12:01:55.4582166Z',
  date: 'Wed, 07 Sep 2016 12:01:55 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .put('/storage-cli-blob-test/pageblobname461317?comp=snapshot')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:01:37 GMT',
  etag: '"0x8D3D716B882EEE8"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fece344f-0001-0017-27ff-0899a7000000',
  'x-ms-version': '2015-04-05',
  'x-ms-snapshot': '2016-09-07T12:01:55.8866198Z',
  date: 'Wed, 07 Sep 2016 12:01:55 GMT' });
 return result; }]];