// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2c224e7e-3ef5-431d-a57b-e71f4662e3a6',
    name: 'Node CLI Test',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: ['mobileservice'],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_TEST_LOCATION'] = 'West Europe';
};

exports.scopes = [[function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .delete('/storage-cli-blob-test/pageblobname461317')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2b7d9e64-0001-004e-6aff-089c21000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:02:59 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/pageblobname461317')
  .reply(200, "", { 'content-length': '512',
  'content-type': 'application/octet-stream',
  'content-md5': 'OToPoPNI+wOHGrk3JgV93A==',
  'last-modified': 'Wed, 07 Sep 2016 12:01:37 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D3D716B882EEE8"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '27f8e4ab-0001-00ee-67ff-085347000000',
  'x-ms-version': '2015-04-05',
  'x-ms-write-protection': 'false',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  date: 'Wed, 07 Sep 2016 12:02:58 GMT' });
 return result; }]];