// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2c224e7e-3ef5-431d-a57b-e71f4662e3a6',
    name: 'Node CLI Test',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: ['mobileservice'],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_TEST_LOCATION'] = 'West Europe';
};

exports.scopes = [[function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/blockblobname69523236')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '56d5f641-0001-0042-45ff-0872d0000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:01:39 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/storage-cli-blob-test/blockblobname69523236', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'aOEJ8PQMpyoV4FzCJ4b45g==',
  'last-modified': 'Wed, 07 Sep 2016 12:01:40 GMT',
  etag: '"0x8D3D716BA64CCD8"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b1836e49-0001-004d-7cff-089f26000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:01:40 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/blockblobname69523236')
  .reply(200, "", { 'content-length': '10',
  'content-type': 'text/plain',
  'content-md5': 'aOEJ8PQMpyoV4FzCJ4b45g==',
  'last-modified': 'Wed, 07 Sep 2016 12:01:40 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D3D716BA64CCD8"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd91e8ede-0001-00b1-14ff-08a1b9000000',
  'x-ms-version': '2015-04-05',
  'x-ms-write-protection': 'false',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  date: 'Wed, 07 Sep 2016 12:01:41 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .put('/storage-cli-blob-test/blockblobname69523236?comp=lease')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Wed, 07 Sep 2016 12:01:40 GMT',
  etag: '"0x8D3D716BA64CCD8"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fbb3663e-0001-0073-5dff-082907000000',
  'x-ms-version': '2015-04-05',
  'x-ms-lease-id': 'ca8ca16a-0722-4fa4-b54b-ecbd8a51fd88',
  date: 'Wed, 07 Sep 2016 12:01:41 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/storage-cli-blob-test/blockblobname69523236', '*')
  .reply(412, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>LeaseIdMissing</Code><Message>There is currently a lease on the blob and no lease ID was specified in the request.\nRequestId:cade7691-0001-0023-35ff-08360f000000\nTime:2016-09-07T12:01:42.0383863Z</Message></Error>", { 'content-length': '267',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'cade7691-0001-0023-35ff-08360f000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:01:41 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/storage-cli-blob-test/blockblobname69523236', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'rG1yD4pD69MsOEPPGr72YA==',
  'last-modified': 'Wed, 07 Sep 2016 12:01:42 GMT',
  etag: '"0x8D3D716BB7DAC43"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '878747af-0001-0101-3cff-081e6c000000',
  'x-ms-version': '2015-04-05',
  date: 'Wed, 07 Sep 2016 12:01:42 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://cliteststorage2874.blob.core.windows.net:443')
  .head('/storage-cli-blob-test/blockblobname69523236')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'text/plain',
  'content-md5': 'rG1yD4pD69MsOEPPGr72YA==',
  'last-modified': 'Wed, 07 Sep 2016 12:01:42 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D3D716BB7DAC43"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '21331f10-0001-007f-6bff-08c7f6000000',
  'x-ms-version': '2015-04-05',
  'x-ms-write-protection': 'false',
  'x-ms-lease-status': 'locked',
  'x-ms-lease-state': 'leased',
  'x-ms-lease-duration': 'infinite',
  'x-ms-blob-type': 'BlockBlob',
  date: 'Wed, 07 Sep 2016 12:01:42 GMT' });
 return result; }]];
 exports.randomTestIdsGenerated = function() { return ['blockblobname69523236'];};