// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: '2c224e7e-3ef5-431d-a57b-e71f4662e3a6',
    name: 'Node CLI Test',
    user: {
      name: 'user@domain.example',
      type: 'user'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: ['mobileservice'],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_TEST_LOCATION'] = 'West Europe';
};

exports.scopes = [[function (nock) { 
var result = 
nock('https://cliteststorage2026.table.core.windows.net:443')
  .get('/Tables')
  .reply(200, "{\"odata.metadata\":\"https://cliteststorage2026.table.core.windows.net/$metadata#Tables\",\"value\":[{\"TableName\":\"storageclitesttable\"}]}", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/json;odata=minimalmetadata;streaming=true;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4f7c0147-0002-00f8-1200-0992d9000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Wed, 07 Sep 2016 12:06:49 GMT' });
 return result; }]];